[build]
  base = "/app"  # Build from the "app" folder
  command = "npm run build"  # Command to build your app
  publish = "/app/build"   # Absolute path in case it's not resolving correctly


[[redirects]]
from = "/*"
to = "/index.html"
status = 200